spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.domain.com/xxx/keys
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:movierama;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: true
