server:
  port: 8080
  max-http-header-size: 10000000 # this is required to handle the long size JWT
  servlet:
    context-path: /movierama
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_HjAf7afig
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:movierama;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: true
